type: l3spine

l3_edge:
  p2p_links:
    - nodes: ['SF-FD-Spine-1', 'WAN-1']
      interfaces: ['Ethernet51/1', 'Ethernet15/1']
      ip: ['10.255.0.29/31', '10.255.0.28/31']
      as: [65350, 64750]
      include_in_underlay_protocol: true
      campus_link_type: ['egress']
    - nodes: ['SF-FD-Spine-2', 'WAN-1']
      interfaces: ['Ethernet51/1', 'Ethernet16/1']
      ip: ['10.255.0.31/31', '10.255.0.30/31']
      as: [65350, 64750]
      include_in_underlay_protocol: true
      campus_link_type: ['egress']
