---
tenants:  # dynamic_key: network_services
  - name: SOMA
    vrfs:
      - name: default
        vrf_vni: 1
        svis:
          - id: 4092
            name: L2_INBAND_MGMT
            enabled: true
            ip_virtual_router_addresses: ['10.1.14.1']
            ip_helpers:
              - ip_helper: 172.16.254.253
            nodes:
              - node: SF-SOMA-Spine-1
                ip_address: 10.1.14.2/24
              - node: SF-SOMA-Spine-2
                ip_address: 10.1.14.3/24
