generate_cv_tags:
  topology_hints: true

# BGP Settings
bgp_default_ipv4_unicast: true
bgp_graceful_restart:
  enabled: true
  restart_time: 300
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200
evpn_hostflap_detection:
  enabled: false

# BFD Settings
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3

# MAC and ARP Timers
custom_structured_configuration_arp:
  aging:
    timeout_default: 5400

# vEOS
p2p_uplinks_mtu: 1500

# Max spines
max_spines: 2

# AVD Settings
# Dump all vars and facts per device after generating `avd_switch_facts`.
avd_eos_designs_debug: false

# Generate structured configuration per device.
avd_eos_designs_structured_config: true

# Unset `avd_switch_facts` to gain a small performance improvement since Ansible needs to handle fewer variables.
avd_eos_designs_unset_facts: true
# Include connected endpoints in the fabric-wide documentation.
eos_designs_documentation:
  connected_endpoints: true
  topology_csv: true
  p2p_links_csv: true

anta_reports_dir_name: "reports"
anta_reports_dir: '{{ root_dir }}/{{ anta_reports_dir_name }}/{{ fabric_name }}'
anta_report_md_path: '{{ anta_reports_dir }}/{{ fabric_name }}-anta-report.md'
anta_report_csv_path: '{{ anta_reports_dir }}/{{ fabric_name }}-anta-report.csv'
anta_runner_batch_size: 16
