---
# validate.yml

- name: Validate State
  hosts: all
  connection: local
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: validate states on EOS devices
      import_role:
         name: arista.avd.anta_runner
