name: Deploy updates

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-prod:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python (from pyproject.toml)
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies with uv
        run: uv sync --all-extras --dev

      - name: Install Arista AVD collection
        working-directory: AVD-Demo
        run: |
          uv run ansible-galaxy collection install -r collections/requirements.yml

      - name: Run AVD Deploy
        working-directory: AVD-Demo
        run: make deploy-auto

  validate_prod:
    needs: deploy-prod
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

#       - name: Install uv
#         uses: astral-sh/setup-uv@v5

#       - name: Set up Python (from pyproject.toml)
#         uses: actions/setup-python@v5
#         with:
#           python-version-file: "pyproject.toml"

#       - name: Install dependencies with uv
#         run: uv sync --all-extras --dev

#       - name: Install Arista AVD collection
#         run: |
#           uv run ansible-galaxy collection install -r collections/requirements.yml

      - name: validate
        working-directory: AVD-Demo
        run: |
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          make validate

      - name: Check for Changes
        id: git-check
        run: |
          git diff --exit-code || echo "changed=true" >> $GITHUB_OUTPUT
          git diff --cached --exit-code || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "ðŸ¤– Automated AVD configuration build [skip ci]"
          git push
